pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    
                    bat 'docker build -t myapp .'

                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    bat 'docker run -d -p 5000:5000 --name devopslab_container devopslab_app'
                }
            }
        }

        stage('Verify Running Container') {
            steps {
                script {
                    bat 'docker ps'
                }
            }
        }
    }

    post {
        always {
            bat 'docker stop devopslab_container || true'
            bat 'docker rm devopslab_container || true'
        }
    }
}
