pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out source code...'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                bat 'docker build -t myapp -f Task1_Docker_Jenkins/Dockerfile Task1_Docker_Jenkins'
            }
        }

        stage('Run Container') {
            steps {
                echo 'Running Docker container...'
                bat 'docker run -d -p 5000:5000 --name devopslab_container myapp'
            }
        }

        stage('Verify Running Container') {
            steps {
                echo 'Verifying container...'
                bat 'docker ps'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up container...'
            bat '''
            docker stop devopslab_container || exit 0
            docker rm devopslab_container || exit 0
            '''
        }
    }
}
